name: CI
on: [push]
jobs:

  build-lnx-bad:
    runs-on: ubuntu-20.04

    steps:

    - uses: actions/checkout@v2
    - name: env/setup
      run: env/setup.sh
    - name: git submodule
      run: env/submodule.sh --jobs 3

    - name: make Linux server
      run: make -j3 -C srv-shared
